### ISSUE TITLE
Different extension compared to the `file` command

### ISSUE THREAD

**Issue by alireza-rezaee** [hey-red/Mime#52]
It seems that an error occurs here and it recognizes the `.gz` as `.bin`. While the [file](https://github.com/file/file) has recognized it correctly. I don't know, doesn't the `file` have an api to get the extension directly? If I understand correctly we are actually using MIME Type mapping as an alternative.

```c#
[Fact]
public void Guess_Gzip_ReturnSameAsNative()
{
    // small gzip file: https://github.com/mathiasbynens/small
    byte[] s_gzipBytes =
    [
        0x1f, 0x8b, 0x08, 0x00, 0xae, 0x86, 0xe1, 0x5b, 0x02, 0x03, 0x03, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00
    ];

    var actualMimeType = GuessMimeType(s_gzipBytes);
    var actualExtension = GuessExtension(s_gzipBytes);

    // $ file gzip.gz --mime
    // → gzip.gz: application/gzip; charset=binary
    string expectedMimeType = "application/gzip";

    // $ file gzip.gz --extension
    // → gzip.gz: gz/tgz/tpz/ipk/vbox-extpack/svgz
    string[] expectedExtensions = [ "gz", "tgz", "tpz", "ipk", "vbox-extpack", "svgz"];

    Assert.Equal(expectedMimeType, actualMimeType);
    Assert.Contains(expectedExtensions, e => e == actualExtension); // ← Exception raised here
}
```

**Assert.Contains() Failure**
```
Assert.Contains() Failure
Not found: (filter expression)
In value:  String[] ["gz", "tgz", "tpz", "ipk", "vbox-extpack", ...]
   at Test.UnitTest.Guess_Gzip_ReturnsSameAsNative() in .../UnitTest.cs:line 28
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

This is probably because [MimeTypesMap](https://github.com/hey-red/MimeTypesMap) — which depends on MIME types known by Apache:
https://github.com/hey-red/Mime/blob/b0582324592c574fda00e0705e4ed036fc918f8e/src/Mime/MimeGuesser.cs#L99

**Comment by hey-red** [comment]
If you want to get extension directly from libmagic:

```C#
using var magic = new Magic(MagicOpenFlags.MAGIC_EXTENSION);
var result = magic.Read(@"/path/to/gzip.gz"); // from file
Console.WriteLine(result); // -> gz/tgz/tpz/ipk/vbox-extpack/svgz/blend/dia/gnucash/rdata/xoj
```

However for this file it doesn't work when the magic_buffer method is used:
```C#
byte[] buf = File.ReadAllBytes(@"/path/to/gzip.gz");
using var magic = new Magic(MagicOpenFlags.MAGIC_EXTENSION);
var result = magic.Read(buf, buf.Length);
Console.WriteLine(result); // -> "???"
```

I have no idea why we have different behaviour..
But I think you can update MimeTypesMap dict, before you get results from MimeGuesser:
`MimeTypesMap.AddOrUpdate("application/gzip", "gz");`
or create your own dictionary with mime<->extensions mapping.

**Comment by alireza-rezaee** [comment]
> byte[] buf = File.ReadAllBytes(@"/path/to/gzip.gz");
> using var magic = new Magic(MagicOpenFlags.MAGIC_EXTENSION);
> var result = magic.Read(buf, buf.Length);
> Console.WriteLine(result); // -> "???"

This difference behavior is strange, but it is OK with this very similar [gzip-name.gz](https://github.com/mathiasbynens/small/blob/master/gzip-name.gz) file:

```shell
$ xxd gzip.gz
00000000: 1f8b 0800 ae86 e15b 0203 0300 0000 0000  .......[........
00000010: 0000 0000                                ....

$ xdd gzip-name.gz
00000000: 1f8b 0808 ae86 e15b 0203 6e00 0300 0000  .......[..n.....
00000010: 0000 0000 0000
```

```c#
// gzip-name.gz
bytes[] fileBytes =
[
    0x1f, 0x8b, 0x08, 0x08, 0xae, 0x86, 0xe1, 0x5b, 0x02, 0x03, 0x6e, 0x00, 0x03, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00
];
using var magic = new Magic(MagicOpenFlags.MAGIC_EXTENSION);
magic.Read(fileBytes, fileBytes.Length) // -> "gz/tgz/tpz/zabw/svgz/adz/kmy/xcfgz"
```
